# Generated by Django 5.2.7 on 2025-10-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chiffrement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('encrypt', 'Chiffrement'), ('decrypt', 'Déchiffrement')], max_length=10)),
                ('texte_clair', models.TextField(blank=True, null=True)),
                ('texte_chiffre', models.TextField(blank=True, null=True)),
                ('date_operation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
